apiVersion: v1
kind: Service
metadata:
  name: pam-gateway-agent
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.agent.service.type }}
  selector:
    app: pam-gateway-agent
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: {{ .Values.agent.service.port }}
