apiVersion: v1
kind: Secret
metadata:
  name: pam-gateway-api-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jiraToken: "{{ .Values.api.jira.token }}"
  jiraWebhookSecret: "{{ .Values.api.jira.webhookSecret }}"
  cmdbToken: "{{ .Values.api.cmdb.token }}"
