apiVersion: v1
kind: Service
metadata:
  name: pam-gateway-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: pam-gateway-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
