{{- if .Values.postgres.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.postgres.pdb.minAvailable }}
  selector:
    matchLabels:
      app: postgres
{{- end }}
