apiVersion: apps/v1
kind: Deployment
metadata:
  name: pam-gateway-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: pam-gateway-ui
  template:
    metadata:
      labels:
        app: pam-gateway-ui
    spec:
      containers:
        - name: pam-gateway-ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: {{ .Values.ui.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.ui.service.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ui.probes.readinessPath }}
              port: {{ .Values.ui.service.targetPort }}
            initialDelaySeconds: {{ .Values.ui.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.probes.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.ui.probes.livenessPath }}
              port: {{ .Values.ui.service.targetPort }}
            initialDelaySeconds: {{ .Values.ui.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.probes.timeoutSeconds }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.ui.service.targetPort }}"
            - name: Api__BaseUrl
              value: "{{ .Values.ui.apiBaseUrl }}"
