apiVersion: v1
kind: Service
metadata:
  name: pam-gateway-ui
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: pam-gateway-ui
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
