apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: pam-gateway
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: pam-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: keycloak-admin
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: pam-gateway
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
